### PCA

In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
import numpy as np


from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.pipeline import make_pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.datasets  import load_diabetes

In [8]:
url = "https://raw.githubusercontent.com/digipodium/Datasets/main/classfication/diabetes.csv"
df = pd.read_csv(url)
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [9]:
X = df.drop(columns=['Outcome'])
y = df.Outcome

In [11]:
scaler = StandardScaler()

In [12]:
df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])

In [15]:
# finding covariance metrix

covariance_matrix = np.cov([df.iloc[:,0], df.iloc[:,1], df.iloc[:,2]])
print('Covariance Matrix:\n', covariance_matrix)

Covariance Matrix:
 [[1.00130378 0.12962746 0.14146618]
 [0.12962746 1.00130378 0.15278853]
 [0.14146618 0.15278853 1.00130378]]


In [16]:
eigen_values, eigen_vector  = np.linalg.eig(covariance_matrix)

In [17]:
eigen_values

array([1.2841027 , 0.87327864, 0.84653   ])

In [18]:
features = PCA(n_components=3).fit_transform(X, y)

In [19]:
px.scatter_3d(x=features[:,0], y = features[:,1], z= features[:,2], color= y.values)

In [22]:
X_train,X_test, y_trian, y_test = train_test_split(features, y.values, test_size=.2, random_state=2)
clf = make_pipeline(StandardScaler(), KNeighborsClassifier())
clf.fit(X_train, y_trian)
y_pred = clf.predict(X_test)
print('Matric\n', confusion_matrix(y_test, y_pred))
print('Report\n', classification_report(y_test, y_pred))

Matric
 [[91 18]
 [21 24]]
Report
               precision    recall  f1-score   support

           0       0.81      0.83      0.82       109
           1       0.57      0.53      0.55        45

    accuracy                           0.75       154
   macro avg       0.69      0.68      0.69       154
weighted avg       0.74      0.75      0.74       154



In [2]:
df = pd.read_csv('test.csv.zip')

In [3]:
df.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [4]:
df.shape

(28000, 784)

In [5]:
df.sample()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
4805       0       0       0       0       0       0       0       0       0   

      pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
4805       0  ...         0         0         0         0         0         0   

      pixel780  pixel781  pixel782  pixel783  
4805         0         0         0         0  

[1 rows x 784 columns]

In [11]:
X = df.iloc[:,1:]
y = df.iloc[:,0]

In [12]:
X_train, X_test, y_trian, y_test = train_test_split(X, y , test_size=0.2, random_state=42)

In [13]:
X_train.shape

(22400, 783)

In [14]:
knn = KNeighborsClassifier()

In [15]:
knn.fit(X_train, y_trian)

KNeighborsClassifier()