### Working with Numpy - for Mathematical Operation

In [26]:
import numpy as np

In [27]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [28]:
b = np.array([[1], [2], [3], [4], [5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [29]:
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)
print(c.shape)
print(c[1][1])             # which meanse the first element of first row

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [30]:
# create Zeros, ones, custom, array
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [31]:
b = np.array((2, 3))
print(b)

[2 3]


In [32]:
# Array for some constant
c = np.full((3, 2), 5)
print(c)

[[5 5]
 [5 5]
 [5 5]]


In [33]:
# Identity metric - Size/Square Matrix
d = np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [34]:
# Random Matrix
randomMatrix = np.random.random((2, 3))
print(randomMatrix)

[[0.11393137 0.03220231 0.11420599]
 [0.34292676 0.52065756 0.12962003]]


In [35]:
# for indecing change
# Slicing operation
print(randomMatrix[:,2])

[0.11420599 0.12962003]


In [36]:
# Slicing example- [2, 1 : 3] - 2 represent row , 1 is indecing and 3 is column 

In [37]:
randomMatrix[1, 1: ] = 1
print(randomMatrix)

[[0.11393137 0.03220231 0.11420599]
 [0.34292676 1.         1.        ]]


In [38]:
# set some rows and columns with any values
z = np.zeros((3, 3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [39]:
# Suppose we have to make 1st row and 2nd column is 5
z[1, :] = 5
print(z)

[[0. 0. 0.]
 [5. 5. 5.]
 [0. 0. 0.]]


In [40]:
z[:,-1] = 7
print(z)

[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


In [41]:
z[1, :] = 5
z[:, -1] = 7
print(z)

[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


In [42]:
# Datatype
z = np.zeros((3,3), dtype=np.int64)
print(z.dtype)

int64


#### Mathematical Operations

In [43]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

# Element wise addition
print(x + y)
print(np.add(x, y))

print(x - y)
print(np.subtract(x, y))

print(x * y)
print(np.multiply(x, y))

print(x / y)
print(np.divide(x, y))
print(np.sqrt(x))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [44]:
# Matrix Multiplication / Dot Products
# print(x, y)
print(x)
print(y)
print(x.dot(y))
print(np.dot(x, y))                          # both line are same output

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [45]:
# Mathematical (Dot Products) of vectors- Scalar 
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])
print(a.dot(b))

30


In [46]:
print(a)
print(sum(a))

[1 2 3 4]
10


In [47]:
print(x)
print(sum(x))
print(np.sum(x))
print(np.sum(x, axis=0))                      # axis = 0 (for row)
print(np.sum(x, axis=1))                      # axis = 1 (for column)

[[1 2]
 [3 4]]
[4 6]
10
[4 6]
[3 7]


In [48]:
# Stacking of Arrays
print(a)
b = b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [49]:
# Combine two arrays in single arrays
a = np.stack((a, b), axis=0)

In [50]:
# Reshape numpy array
print(a)

[[ 1  2  3  4]
 [ 1  4  9 16]]


In [51]:
# above output has 8 elements and suppose we have to change this shape as (4, 2)
c = a.reshape((4, 2))
print(c)

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


In [52]:
c = a.reshape((8, 1))
print(c)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 1]
 [ 4]
 [ 9]
 [16]]


In [53]:
c = a.reshape((8,))
print(a)

[[ 1  2  3  4]
 [ 1  4  9 16]]


In [54]:
c = c.reshape((-1, 4))
print(c)

[[ 1  2  3  4]
 [ 1  4  9 16]]


### NUMPY RANDOM MODULE

- rand : Random value in a given shape.
- randn : Return a sample (or samples) from the "standard nomral" distribution.
- randint : Return random integers from low (inclusive) to high (exclusive)
- random : Return random floats in the half- open interval [0.0, 1.0)
- choice : Generates a random sample from a given 1-D array.
- Shuffle : Shuffles the contents of a sequence.

In [55]:
# Suppose we want to generate an array from a given range
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [56]:
a = np.arange(10) + 5            # means indecing start from 5            
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [57]:
# Shuffle array randomly
np.random.shuffle(a)
print(a)

[ 5  9 14 11 12 10 13  7  8  6]


In [58]:
a = np.random.rand(2, 3)
print(a)

[[0.20010957 0.15129063 0.04614228]
 [0.959263   0.33515729 0.18986066]]


In [59]:
# Returns values from a Standard Normal Distributions
a = np.random.randn(2, 3)
print(a)

[[ 0.03664331  0.87741941 -0.61347173]
 [ 0.09116594  0.94161914 -0.01448012]]


In [60]:
a = np.random.randint(5, 10, 2)
print(a)

[5 8]


In [61]:
# Randomly pick one element from a array
element = np.random.choice([1, 4, 3, 2, 11, 27])
print(element)

3


In [62]:
# Seed concept
np.random.seed(1)
np.random.shuffle(a)
print(a)

[5 8]


### Some more numpy functions - Statistics

- min, max
- mean
- median
- average
- variance
- standard deviation

In [63]:
a = np.array([[1, 2, 3, 4], [7, 6, 2, 0]])
print(a)

[[1 2 3 4]
 [7 6 2 0]]


In [64]:
print(np.min(a))
# Specify axis for the direction in case of multidim array
print(np.min(a, axis=0))
print(np.max(a, axis=1))

0
[1 2 2 0]
[4 7]


In [65]:
b = np.array([1, 2, 3, 4, 5])
m = sum(b)/5
print(m)
print(np.mean(b))
print(np.mean(a, axis = 0))
print(np.mean(a, axis = 1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [66]:
c = np.array([1, 5, 4, 2, 0])
print(np.median(c))

2.0


In [67]:
# Mean vs Average (slide Difference)
print(np.mean(c))

2.4


In [68]:
weight = np.array([1, 2, 3, 4, 5])
print(np.average(c, weights= weight))

2.066666666666667


In [69]:
weight = np.array([1, 1, 1, 1, 1])
print(np.average(c, weights= weight))

2.4


In [70]:
# Standard Deviation
u = np.mean(c)
mystd = np.sqrt(np.mean(abs(c-u)**2))
print(mystd)

1.854723699099141


In [71]:
# In-built function
dev = np.std(c)
print(dev)

1.854723699099141


In [72]:
# Variance
print(mystd**2)
print(np.var(c))

3.440000000000001
3.4400000000000004
